apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  labels:
    app: asterisk
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5060
